#!/usr/bin/env bash
# Script that installs Nginx and configure it
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
new="location /redirect_me {\n \treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "26i $new" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
