#!/usr/bin/env bash
# install nginx and change the default page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
new_config="\\\n\terror_page 404 /custom_404.html;\n"
file="/etc/nginx/sites-enabled/default"
sudo sed -i "43i $new_config" $file
sudo service nginx restart
