#!/usr/bin/env bash
# install nginx and change the default page
my_config="a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\tadd_header X-Served-By \"\$HOSTNAME\";"

apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _;/$my_config" /etc/nginx/sites-available/default
service nginx restart
