#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
FRONTEND="frontend 2642-lb-01\n\tbind *:80\n\tdefault_backend nginx_pool\n"
BACKEND="backend nginx_pool\n\tbalance roundrobin\n\tmode http\n\tserver 2642-web-01 34.139.123.27:80 check\n\tserver 2642-web-02 34.73.206.129:80 check\n"
sudo echo -e $FRONTEND >> /etc/haproxy/haproxy.cfg
sudo echo -e $BACKEND >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
