#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times, but for the 9th

i=0
while ((i<10))
do
      if ((i==9))
then
	  echo "Hi"
      fi
      echo "Holberton School"
      ((i++))
done
