#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:

i=1
while((i<11))
do
    if ((i==4))
then
	echo "bad luck"
    elif ((i==8))
then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
