#!/usr/bin/env bash
# Write a Bash script that gives you information about the holbertonschool file
File="holbertonschool"
if [ -e $File ]
then
    echo "holbertonschool file exists"
    if [ -s $File ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f $File ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi