#!/usr/bin/env bash
# nginx on port 8080
sudo pkill -f apache2
sudo chmod ugo+rw /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart